---
title: "Group Project"
format: html
editor: visual
---

## Introduction hello Can you see this??????

Title for the project: Review of Connecticut's Lake systems focusing in geography, aquatic life, and regional impact.

Group Members: Maddy Shantz, Abby Nolan, Sofia Gee

Class: **Data-412**

### **Data Sets:**

- 305b assessed 2012 lake
- 305b assessed 2006 lake


The datasets include: OBJECTID, CT LAKE ID, 305B ID, Name, Location, Acres, Aquatic Life, Recreation, Fish Consumption, Cycle, Drinking Water Supply, Shape_Area, and Shape_Length

## Description of the problems/questions addressed (Abby and Sofia) <- A description of the problem/questions to be addressed.

Make them specific and connect to measures in your data set. Where appropriate, write

these as formal tests of hypotheses.

1.  How are aquatic life support and drinking water supply correlated in the years 2006 and 2012?

2.  Do the regions where the lakes are located have an impact on the aquatic life support and drinking water supply correlation?

3.  How have the length and area changed over time?

## Peer-reviewed articles: (Covered by Maddy)

#### [Concerns and Threats of Contamination on Aquatic Ecosystems](https://pmc.ncbi.nlm.nih.gov/articles/PMC7121614/)

Authors: [Ishrat Bashir](https://pubmed.ncbi.nlm.nih.gov/?term=%22Bashir%20I%22%5BAuthor%5D) ^4,✉^, [F A Lone](https://pubmed.ncbi.nlm.nih.gov/?term=%22Lone%20FA%22%5BAuthor%5D) ^4^, [Rouf Ahmad Bhat](https://pubmed.ncbi.nlm.nih.gov/?term=%22Bhat%20RA%22%5BAuthor%5D) ^4^, [Shafat A Mir](https://pubmed.ncbi.nlm.nih.gov/?term=%22Mir%20SA%22%5BAuthor%5D) ^4^, [Zubair A Dar](https://pubmed.ncbi.nlm.nih.gov/?term=%22Dar%20ZA%22%5BAuthor%5D) ^4^, [Shakeel Ahmad Dar](https://pubmed.ncbi.nlm.nih.gov/?term=%22Dar%20SA%22%5BAuthor%5D) ^4^

**Brief Summary:** water contamination is the outcome associated with human activities like urbanization, industrialization, and agricultural activities. Specific contaminants are from the overuse of pesticides, fertilizers, and sewage from industrial and residential areas. There is a need for regular monitoring and controlling of pollutant discharge into the nearby aquatic environs.

#### State of the World's Freshwater Ecosystems: Physical, Chemical, and Biological Changes

Authors: Stephen R. Carpenter, Emily H. Stanley, and M. Jake Vander Zanden

```         
```

###Data 1 
Evidence that you have downloaded the data you will work on. Give the source(s) with

link(s) to your data and explore some features of the raw data set(s).

insert data sets
try a filter / mutuate / merge function to combine the data sets OR describe how you would do that

``` {r}
library(tidyverse)
twelve_lakes <- read_csv("2012.csv")
six_lakes <- read_csv("2006.csv")
total_lakes <- bind_rows(six_lakes, twelve_lakes)
```

###Data 2 (1-3 Sofia, 4-6 Maddy)
Provide code for and address the following items as you get to know your data. Use the original data set(s) you downloaded to answer these questions:
1. Who are the individuals under study in this data set? That is, what does each row of your data set correspond to? (These do not have to be people!)
2. How many individuals are in your study?
3. Are there repeated measurements on individuals? (Such as measurements takenover time on the same individual?) 
4. How many total variables are in the data set? Which variables are of interest to you? How does each variable connect to your specific questions?
5. What data tidying steps do you anticipate having to do to get a clean data set forthe remaining analyses?
6. For some groups, how do you plan to combine from different data sets?


## Member's tasks

Give details on who is expected to be responsible for these next projects steps and when

you anticipate working on them (note that multiple people can be responsible for the

same step):

– Data preparation: Cleaning and tidying the data (Sofia, Abby, Maddy - due Friday, Julyn 24th, will specify what we work on as we complete this step)

– Statistical Methods: EDA and any statistical analyses (Shared, due July 31)

– Producing the group report (shared effort, broken down by sections worked on in data preparation, due August 9th)

– Producing the group presentation (shared based on what parted each person worked on, due August 7th)

– Rehearsing the presentation (shared, due Aug 7th)

– A list of who is responsible for submitting which deliverables in Canvas. (Maddy will submit the progress report, Abby will submit the slides and Sofia will submit the report on August 9th)




